typedef char* string;
#define PI 3.14159265359
//Define keys
#define ENTER_KEY_CODE 0x1C
#define BACKSPACE_KEY_CODE 0x0E
#define LEFTSHIFT_KEY_CODE 0x2A
#define CAPSLOCK_KEY_CODE 0x3A
#define UPARROW_KEY_CODE 0xC8
#define DOWNARROW_KEY_CODE 0xD0
#define LEFTARROW_KEY_CODE 0xCB
#define RIGHTARROW_KEY_CODE 0xCD